# Mostly copied from https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
# zlatinb

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: dependencies
        run: sudo apt install gettext golang-go git ant && go install github.com/mediabuyerbot/go-crx3/crx3@latest && go install github.com/eyedeekay/amo-version@latest && go install github.com/delicb/dzip@latest
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name : Generate override.properties
        run: |
          rm -f override.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "noExe=true" >> override.properties
      - name: build with Ant
        run: ant distclean jar
      - name: Upload installer.jar
        uses: actions/upload-artifact@v2
        with:
          name: I2P-install.jar-${{ github.sha }}
          path: install.jar
        

