# Mostly copied from i2p.i2p, by way of: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant
# zlatinb did it originally, now I maintain it(idk)

name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: dependencies
        run: sudo apt install gettext golang-go git ant
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name : Generate override.properties
        run: |
          rm -f override.properties
          echo "build.built-by=GitHub Actions" >> override.properties
          echo "noExe=true" >> override.properties
      - name: install crx3
        run: go install github.com/mediabuyerbot/go-crx3/crx3@latest
      - name: install dzip
        run: go install github.com/delicb/dzip@latest
      - name: install amo-version
        run: go install github.com/eyedeekay/amo-version@a4f4119eac453a14d6b6184b656320eb72b5da3c
      - name: build with Ant
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          ant distclean jar
      - name: Upload Firefox Profile Strict
        uses: actions/upload-artifact@v2
        with:
          name: i2p.firefox.base.profile.zip-${{ github.sha }}
          path: ./src/i2p.firefox.base.profile.zip
      - name: Upload Firefox Profile Usability
        uses: actions/upload-artifact@v2
        with:
          name: i2p.firefox.usability.profile.zip-${{ github.sha }}
          path: ./src/i2p.firefox.usability.profile.zip
        

