name: Release

#on: [push]

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*.*' # Release 1.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ant.yml
          if_no_artifact_found: fail
      - name: List artifacts
        run: ls -lah
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*"
          bodyFile: "CHANGES.md"
