name: Release

#on: [push]

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*.*.*' # Release 1.2.3

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            CHANGES.md
          sparse-checkout-cone-mode: false
      - name: sleep 5 minutes
        run: |
          echo "sleeping 5 minutes to wait for artifacts"
          sleep 1m
          echo "sleeping 4 minutes to wait for artifacts"
          sleep 1m
          echo "sleeping 3 minutes to wait for artifacts"
          sleep 1m
          echo "sleeping 2 minutes to wait for artifacts"
          sleep 1m
          echo "sleeping 1 minutes to wait for artifacts"
          sleep 1m
      - name: Download artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          skip_unpack: true
          workflow: ant.yml
          if_no_artifact_found: fail
      - name: List artifacts
        run: |
          echo "" >> CHANGES.md
          echo "## Checksums" >> CHANGES.md
          echo "" >> CHANGES.md
          echo "```" >> CHANGES.md
          sha256sum *.* >> CHANGES.md
          echo "```" >> CHANGES.md
          echo "" >> CHANGES.md
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.*"
          bodyFile: "CHANGES.md"
