name: Release

on: [push]

#on:
  #push:
    # Sequence of patterns matched against refs/tags
    # tags:
      #- '*.*.*' # Release 1.2.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ant.yml
          if_no_artifact_found: fail
      - name: List artifacts
        run: ls -lah